[General]
SyntaxVersion=2
BeginHotkey=119
BeginHotkeyMod=0
PauseHotkey=0
PauseHotkeyMod=0
StopHotkey=123
StopHotkeyMod=0
RunOnce=1
EnableWindow=
MacroID=0902f85a-3971-4be6-8d31-88945c6bb775
Description=¦Û°ÊÂIÆp¥Û
Enable=1
AutoRun=0
[Repeat]
Type=0
Number=1
[SetupUI]
Type=2
QUI=
[Relative]
SetupOCXFile=
[Comment]

[Script]
MoveTo 1064,549
For 99
    Delay 100
    LeftClick 1
Next
MoveTo 963,356
For 99
    Delay 100
    LeftClick 1
Next
MoveTo 850,547
For 99
    Delay 100
    LeftClick 1
Next
